name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci
      - run: npm run build

      - name: Install s3cmd
        run: sudo apt-get install -y s3cmd

      - name: Install Scaleway CLI
        uses: scaleway/action-scw@v0
        with:
          version: v2.37.0

      - name: Deploy to Object Storage
        run: |
          scw object config get type=s3cmd region=fr-par > ~/.s3cfg
          s3cmd --no-mime-magic --guess-mime-type --acl-public sync --delete-removed ./dist/ s3://techify.fatus.eu/
        env:
          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
          SCW_DEFAULT_PROJECT_ID: ${{ secrets.SCW_DEFAULT_PROJECT_ID }}
          SCW_DEFAULT_ORGANIZATION_ID: ${{ secrets.SCW_DEFAULT_ORGANIZATION_ID }}
          SCW_DEFAULT_REGION: fr-par

      - name: Purge Edge Services cache
        run: scw edge-services purge-request create pipeline-id=${{ secrets.SCW_PIPELINE_ID }} all=true
        env:
          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
          SCW_DEFAULT_PROJECT_ID: ${{ secrets.SCW_DEFAULT_PROJECT_ID }}
          SCW_DEFAULT_ORGANIZATION_ID: ${{ secrets.SCW_DEFAULT_ORGANIZATION_ID }}
